---
sudo: required
dist: trusty

cache:
  directories:
  - $HOME/.vagrant.d/boxes

install:
  - sudo pip install ansible
  - sudo apt-get install virtualbox-qt
  - sudo apt-get install vagrant
#  - echo -e 'localhost  ansible_connection=local' > spec/inventory
#  - echo -e '[defaults]\nroles_path = ../\nhostfile = ./spec/inventory' > ansible.cfg

script:
  - "./run_specs.sh"
  # Role idempotence
  - "vagrant provision | tee rerun.log"
  - "cat rerun.log | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)"

#  - "ansible-playbook $SITE_AND_INVENTORY --syntax-check"
#  - "ansible-playbook $SITE_AND_INVENTORY --connection=local -vvv --sudo"
#  - "bundle install --path vendor/bundle"
#  - "SPEC_BACKEND_EXEC=yes bundle exec rspec spec"
#  # Role idempotence
#  - "ansible-playbook $SITE_AND_INVENTORY --connection=local -vvv --sudo | tee rerun.log"
#  - "cat rerun.log | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)"