---
language: "python"
python: "2.7"

env:
  - SITE_AND_INVENTORY="spec/test.yml -i spec/inventory"

install:
  - pip install ansible
  - echo -e 'localhost  ansible_connection=local' > spec/inventory
  - echo -e '[defaults]\nroles_path = ../\nhostfile = ./spec/inventory' > ansible.cfg

script:
  - "ansible-playbook $SITE_AND_INVENTORY --syntax-check"
  - "ansible-playbook $SITE_AND_INVENTORY --connection=local -vvv --sudo"
  # Role idempotence
  - "ansible-playbook $SITE_AND_INVENTORY --connection=local -vvv --sudo"
  - "ansible-playbook $SITE_AND_INVENTORY --connection=local -vvv --sudo > rerun.log"
  - "cat rerun.log"
  - "cat rerun.log | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)"