---
sudo: required
dist: trusty

cache:
  directories:
  - $HOME/.vagrant.d/boxes

before_install:
  - curl http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc | sudo apt-key add -
  - echo "deb http://download.virtualbox.org/virtualbox/debian trusty contrib" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get -qq update
  - sudo apt-get install -y virtualbox-5.0 vagrant
  - sudo /etc/init.d/vboxdrv setup

install:
  - sudo pip install ansible
#  - echo -e 'localhost  ansible_connection=local' > spec/inventory
#  - echo -e '[defaults]\nroles_path = ../\nhostfile = ./spec/inventory' > ansible.cfg

script:
  - "./run_specs.sh"
  # Role idempotence
  - "vagrant provision | tee rerun.log"
  - "cat rerun.log | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)"

#  - "ansible-playbook $SITE_AND_INVENTORY --syntax-check"
#  - "ansible-playbook $SITE_AND_INVENTORY --connection=local -vvv --sudo"
#  - "bundle install --path vendor/bundle"
#  - "SPEC_BACKEND_EXEC=yes bundle exec rspec spec"
#  # Role idempotence
#  - "ansible-playbook $SITE_AND_INVENTORY --connection=local -vvv --sudo | tee rerun.log"
#  - "cat rerun.log | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)"