- name: Remove system ruby
  apt: name=ruby state=absent
  with_items:
    - ruby
    - ruby-dev

- name: Install software-properties-common
  apt: name=software-properties-common state=present
  with_items:
    - software-properties-common

- name: add brightbox ruby-ng repo
  apt_repository: repo='ppa:brightbox/ruby-ng' update_cache=yes
  when: ansible_distribution_major_version != '16'

- name: add brightbox ruby-ng-experimental repo
  apt_repository: repo='ppa:brightbox/ruby-ng-experimental' update_cache=yes
  when: ansible_distribution_major_version == '16'

- name: Install brightbox ruby
  apt: name={{item}} state=present
  notify: switch ruby
  with_items:
    - "ruby{{app_ruby_version}}"
    - "ruby{{app_ruby_version}}-dev"
    - ruby-switch

- name: Install rubygems
  apt: name=rubygems1.8 state=present
  when: ansible_distribution_major_version != '16' and app_ruby_version  == '1.8'
