- name: set RAILS_ENV in .bashrc
  lineinfile: dest=/home/{{app_deploy_name}}/.bashrc insertafter="^# for examples" regexp="RAILS_ENV=" line="export RAILS_ENV=production"

- stat: path=/home/{{app_deploy_name}}/.env
  register: env_file

- name: create .env
  file: path=/home/{{app_deploy_name}}/.env state=touch
  when: not env_file.stat.exists

- name: set owner and group for .env
  file: path=/home/{{app_deploy_name}}/.env owner={{app_deploy_name}} group={{app_deploy_name}} mode=0644

- name: set app enviroment variables
  lineinfile: dest=/home/{{app_deploy_name}}/.env regexp="{{ item.key }}=" line="export {{ item.key }}=\"{{ item.value }}\""
  with_dict: "{{app_env}}"

- name: Include application environment variables in the bashrc
  blockinfile:
    dest: /home/{{app_deploy_name}}/.bashrc
    insertbefore: "BOF"
    state: present
    block: |
      if [ -f "$HOME/.env" ] ; then
        . "$HOME/.env"
      fi