- name: Install Bundler
  gem: name=bundler user_install=yes state=present
  become: yes
  become_user: "{{app_deploy_name}}"

- name: add user gems path to .bashrc
  lineinfile: dest=/home/{{app_deploy_name}}/.bashrc line="PATH=\"$(ruby -rubygems -e 'puts Gem.user_dir')/bin:$PATH\"" insertbefore=BOF